auto: true
timezone: America/New_York

#site settings
title: Adrian Ogletree
email: adrianogletree@gmail.com	

skype-url: callTo://adrian.ogletree
linkedin-url: https://www.linkedin.com/pub/adrian-ogletree/16/285/41b
instagram-url: http://instagram.com/atogletree
github-user: aogletree
github-url: http://github.com/
github-repo: http://github.com/aogletree/aogletree.github.io
twitter-user: oftheadriatic
twitter-url: http://twitter.com/